storePassword=Somu@2811
keyPassword=Somu@2811
keyAlias=upload
# Use the full path (use double backslashes)
storeFile=C:\\Users\\veena\\Desktop\\pixelS\\pixelshrink-android\\android\\app\\upload-keystore.jks